voting:
  image:
    repository: deepak25404/examplevotingapp_vote
    voting_tag: "10166034627"
  replicaCount: 1

result:
  image:
    repository: deepak25404/examplevotingapp_result
    result_tag: "10166109308"
  replicaCount: 1

worker:
  image:
    repository: deepak25404/examplevotingapp_worker
    worker_tag: "10166148191"
  replicaCount: 1
